### ISSUE TITLE
Open pull request

### ISSUE THREAD

**Issue by trallarn** [adrianjost/files-sync-action#186]
Would it be possible for this action to create a PR instead of committing to a branch on the target repository?

**Comment by adrianjost** [comment]
It's currently using plain git terminal commands, so it might be a bit more difficult to integrate the Github API to create pull requests instead of commits. But theoretically there's nothing blocking it.

I just don't have any more time to maintain this action or even implement new features. But PRs are very welcome, if you would like to give this idea a go. 🚀

**Comment by trallarn** [comment]
Got it. Thank you @adrianjost 👍
